/* Generated By:JavaCC: Do not edit this line. SimpleConstants.java */
package uniandes.teolen.parserJavaCC.parserProyecto1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BIBTYPE = 5;
  /** RegularExpression Id. */
  int END = 6;
  /** RegularExpression Id. */
  int TITLE = 7;
  /** RegularExpression Id. */
  int AUTHOR = 8;
  /** RegularExpression Id. */
  int JOURNAL = 9;
  /** RegularExpression Id. */
  int YEAR = 10;
  /** RegularExpression Id. */
  int VOLUME = 11;
  /** RegularExpression Id. */
  int EDITOR = 12;
  /** RegularExpression Id. */
  int NUMBER = 13;
  /** RegularExpression Id. */
  int PGS = 14;
  /** RegularExpression Id. */
  int MONTH = 15;
  /** RegularExpression Id. */
  int DPI = 16;
  /** RegularExpression Id. */
  int NOTE = 17;
  /** RegularExpression Id. */
  int KEY = 18;
  /** RegularExpression Id. */
  int PUBLISHER = 19;
  /** RegularExpression Id. */
  int SERIES = 20;
  /** RegularExpression Id. */
  int ADDRESS = 21;
  /** RegularExpression Id. */
  int EDITION = 22;
  /** RegularExpression Id. */
  int URL = 23;
  /** RegularExpression Id. */
  int HPUBLISH = 24;
  /** RegularExpression Id. */
  int TYP = 25;
  /** RegularExpression Id. */
  int CHAPTER = 26;
  /** RegularExpression Id. */
  int ORGA = 27;
  /** RegularExpression Id. */
  int BOOKTITLE = 28;
  /** RegularExpression Id. */
  int SCHOOL = 29;
  /** RegularExpression Id. */
  int INSTITUTION = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int INT = 32;
  /** RegularExpression Id. */
  int NAME = 33;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<BIBTYPE>",
    "\"END\"",
    "\"title\"",
    "\"author\"",
    "\"journal\"",
    "\"year\"",
    "\"volume\"",
    "\"editor\"",
    "\"number\"",
    "\"pages\"",
    "\"month\"",
    "\"doi\"",
    "\"note\"",
    "\"key\"",
    "\"publisher\"",
    "\"series\"",
    "\"address\"",
    "\"edition\"",
    "\"url\"",
    "\"howPublished\"",
    "\"type\"",
    "\"chapter\"",
    "\"organization\"",
    "\"booktitle\"",
    "\"school\"",
    "\"institution\"",
    "<DIGIT>",
    "<INT>",
    "<NAME>",
    "\"={\"",
    "\"}\"",
    "\"= { \"",
    "\" }\"",
    "\"{\"",
    "\",\"",
    "\"};\"",
  };

}
