/* Generated By:JavaCC: Do not edit this line. SimpleConstants.java */
package uniandes.teolen.parserJavaCC.parserProyecto1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BEGIN = 5;
  /** RegularExpression Id. */
  int ARTICLE = 6;
  /** RegularExpression Id. */
  int BOOK = 7;
  /** RegularExpression Id. */
  int BOOKLET = 8;
  /** RegularExpression Id. */
  int CONFERENCE = 9;
  /** RegularExpression Id. */
  int INBOOK = 10;
  /** RegularExpression Id. */
  int INCOLLECTION = 11;
  /** RegularExpression Id. */
  int INPROCEEDINGS = 12;
  /** RegularExpression Id. */
  int MANUAL = 13;
  /** RegularExpression Id. */
  int MASTERSTHESIS = 14;
  /** RegularExpression Id. */
  int MISC = 15;
  /** RegularExpression Id. */
  int PHDTHESIS = 16;
  /** RegularExpression Id. */
  int PROCEEDINGS = 17;
  /** RegularExpression Id. */
  int TECHREPORT = 18;
  /** RegularExpression Id. */
  int UNPUBLISHED = 19;
  /** RegularExpression Id. */
  int END = 20;
  /** RegularExpression Id. */
  int DIGIT = 21;
  /** RegularExpression Id. */
  int INT = 22;
  /** RegularExpression Id. */
  int NAME = 23;
  /** RegularExpression Id. */
  int FIELDVALUE = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"BEGIN\"",
    "\"article\"",
    "\"book\"",
    "\"booklet\"",
    "\"conference\"",
    "\"inbook\"",
    "\"incollection\"",
    "\"inproceedings\"",
    "\"manual\"",
    "\"mastersthesis\"",
    "\"misc\"",
    "\"phdthesis\"",
    "\"proceedings\"",
    "\"techreport\"",
    "\"unpublished\"",
    "\"END\"",
    "<DIGIT>",
    "<INT>",
    "<NAME>",
    "<FIELDVALUE>",
    "\"=\"",
    "\";\"",
  };

}
